### PR TITLE
Added full support for localization and community e-mail configuration

### PR DESCRIPTION
**Pull request by bgaprogrammer**
I've changed all the fixed strings inside the view/index to allow them to be localized. I also added a configuration field to set the community support e-mail, that is for the case when the API call fail, so there will be a way to notify the user that he/she can send an e-mail to get his/her invitation processed.

You will also find an empty "index.html", I added that page because some hosters like Microsoft Azure requires an entry point to understand the application is answering the calls, if the page does not exist automatically, IISNode returns an error. It can be configured on IISNode but the configuration is very complex.

Also added localization strings for Spanish language and the protocol independent support for google fonts.

Finally, I checked the indentation of the .js files and changed it to the standard tab usage.

### CODE REVIEW

**Comment by jramirezdev** [comment]
Forgot to mention, I added localization for Spanish language.

**Comment by outsideris** [comment]
Thank you for great PR. Please don't you change indentations. I think some changes are just indentations that are changed. It makes me hard to read your changes.

Also, why do you change the main background image?

**Comment by bgaprogrammer** [comment]
@outsideris About the indentation, As I said before, I used the standard indentation preferred by many IDE/Editors for javascript and json, if you check again your indentations in many cases are customized and no standard ones. It will take me a long time to revert all the changes, I think the indentations at the end are not so bad compared to the effort of reverting all the way back. Anyway it is up to you which way yo prefer.

About the background image I did not notice the change, so it was not intentional changed. Just a mistake on my local repo changes.

**Comment by outsideris** [comment]
@jramirezdev Most important for code convention is following the same convention in the project. So, your code should follow the convention like indentation. I think that fixing indentation doesn't take a long time. You shouldn't revert all you work, just fix the indentation.

And remove the background image.

**Pull request closed without merging**
